//
// Copyright (C) 1993-1996 Id Software, Inc.
// Copyright (C) 2019-2020 Nobuaki Tanaka
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//


using System;

namespace ManagedDoom.UserInput
{
    public static class DoomKeyEx
    {
        public static char GetChar(this DoomKey key)
        {
            return key switch
            {
                DoomKey.A         => 'a',
                DoomKey.B         => 'b',
                DoomKey.C         => 'c',
                DoomKey.D         => 'd',
                DoomKey.E         => 'e',
                DoomKey.F         => 'f',
                DoomKey.G         => 'g',
                DoomKey.H         => 'h',
                DoomKey.I         => 'i',
                DoomKey.J         => 'j',
                DoomKey.K         => 'k',
                DoomKey.L         => 'l',
                DoomKey.M         => 'm',
                DoomKey.N         => 'n',
                DoomKey.O         => 'o',
                DoomKey.P         => 'p',
                DoomKey.Q         => 'q',
                DoomKey.R         => 'r',
                DoomKey.S         => 's',
                DoomKey.T         => 't',
                DoomKey.U         => 'u',
                DoomKey.V         => 'v',
                DoomKey.W         => 'w',
                DoomKey.X         => 'x',
                DoomKey.Y         => 'y',
                DoomKey.Z         => 'z',
                DoomKey.Num0      => '0',
                DoomKey.Num1      => '1',
                DoomKey.Num2      => '2',
                DoomKey.Num3      => '3',
                DoomKey.Num4      => '4',
                DoomKey.Num5      => '5',
                DoomKey.Num6      => '6',
                DoomKey.Num7      => '7',
                DoomKey.Num8      => '8',
                DoomKey.Num9      => '9',
                DoomKey.LBracket  => '[',
                DoomKey.RBracket  => ']',
                DoomKey.Semicolon => ';',
                DoomKey.Comma     => ',',
                DoomKey.Period    => '.',
                DoomKey.Quote     => '"',
                DoomKey.Slash     => '/',
                DoomKey.Backslash => '\\',
                DoomKey.Equal     => '=',
                DoomKey.Hyphen    => '-',
                DoomKey.Space     => ' ',
                DoomKey.Add       => '+',
                DoomKey.Subtract  => '-',
                DoomKey.Multiply  => '*',
                DoomKey.Divide    => '/',
                DoomKey.Numpad0   => '0',
                DoomKey.Numpad1   => '1',
                DoomKey.Numpad2   => '2',
                DoomKey.Numpad3   => '3',
                DoomKey.Numpad4   => '4',
                DoomKey.Numpad5   => '5',
                DoomKey.Numpad6   => '6',
                DoomKey.Numpad7   => '7',
                DoomKey.Numpad8   => '8',
                DoomKey.Numpad9   => '9',
                _                 => '\0'
            };
        }

        public static string ToString(DoomKey key)
        {
            return key switch
            {
                DoomKey.A         => "a",
                DoomKey.B         => "b",
                DoomKey.C         => "c",
                DoomKey.D         => "d",
                DoomKey.E         => "e",
                DoomKey.F         => "f",
                DoomKey.G         => "g",
                DoomKey.H         => "h",
                DoomKey.I         => "i",
                DoomKey.J         => "j",
                DoomKey.K         => "k",
                DoomKey.L         => "l",
                DoomKey.M         => "m",
                DoomKey.N         => "n",
                DoomKey.O         => "o",
                DoomKey.P         => "p",
                DoomKey.Q         => "q",
                DoomKey.R         => "r",
                DoomKey.S         => "s",
                DoomKey.T         => "t",
                DoomKey.U         => "u",
                DoomKey.V         => "v",
                DoomKey.W         => "w",
                DoomKey.X         => "x",
                DoomKey.Y         => "y",
                DoomKey.Z         => "z",
                DoomKey.Num0      => "num0",
                DoomKey.Num1      => "num1",
                DoomKey.Num2      => "num2",
                DoomKey.Num3      => "num3",
                DoomKey.Num4      => "num4",
                DoomKey.Num5      => "num5",
                DoomKey.Num6      => "num6",
                DoomKey.Num7      => "num7",
                DoomKey.Num8      => "num8",
                DoomKey.Num9      => "num9",
                DoomKey.Escape    => "escape",
                DoomKey.LControl  => "lcontrol",
                DoomKey.LShift    => "lshift",
                DoomKey.LAlt      => "lalt",
                DoomKey.LSystem   => "lsystem",
                DoomKey.RControl  => "rcontrol",
                DoomKey.RShift    => "rshift",
                DoomKey.RAlt      => "ralt",
                DoomKey.RSystem   => "rsystem",
                DoomKey.Menu      => "menu",
                DoomKey.LBracket  => "lbracket",
                DoomKey.RBracket  => "rbracket",
                DoomKey.Semicolon => "semicolon",
                DoomKey.Comma     => "comma",
                DoomKey.Period    => "period",
                DoomKey.Quote     => "quote",
                DoomKey.Slash     => "slash",
                DoomKey.Backslash => "backslash",
                DoomKey.Tilde     => "tilde",
                DoomKey.Equal     => "equal",
                DoomKey.Hyphen    => "hyphen",
                DoomKey.Space     => "space",
                DoomKey.Enter     => "enter",
                DoomKey.Backspace => "backspace",
                DoomKey.Tab       => "tab",
                DoomKey.PageUp    => "pageup",
                DoomKey.PageDown  => "pagedown",
                DoomKey.End       => "end",
                DoomKey.Home      => "home",
                DoomKey.Insert    => "insert",
                DoomKey.Delete    => "delete",
                DoomKey.Add       => "add",
                DoomKey.Subtract  => "subtract",
                DoomKey.Multiply  => "multiply",
                DoomKey.Divide    => "divide",
                DoomKey.Left      => "left",
                DoomKey.Right     => "right",
                DoomKey.Up        => "up",
                DoomKey.Down      => "down",
                DoomKey.Numpad0   => "numpad0",
                DoomKey.Numpad1   => "numpad1",
                DoomKey.Numpad2   => "numpad2",
                DoomKey.Numpad3   => "numpad3",
                DoomKey.Numpad4   => "numpad4",
                DoomKey.Numpad5   => "numpad5",
                DoomKey.Numpad6   => "numpad6",
                DoomKey.Numpad7   => "numpad7",
                DoomKey.Numpad8   => "numpad8",
                DoomKey.Numpad9   => "numpad9",
                DoomKey.F1        => "f1",
                DoomKey.F2        => "f2",
                DoomKey.F3        => "f3",
                DoomKey.F4        => "f4",
                DoomKey.F5        => "f5",
                DoomKey.F6        => "f6",
                DoomKey.F7        => "f7",
                DoomKey.F8        => "f8",
                DoomKey.F9        => "f9",
                DoomKey.F10       => "f10",
                DoomKey.F11       => "f11",
                DoomKey.F12       => "f12",
                DoomKey.F13       => "f13",
                DoomKey.F14       => "f14",
                DoomKey.F15       => "f15",
                DoomKey.Pause     => "pause",
                _                 => "unknown"
            };
        }

        public static DoomKey Parse(ReadOnlySpan<char> value)
        {
            return value switch
            {
                "a"         => DoomKey.A,
                "b"         => DoomKey.B,
                "c"         => DoomKey.C,
                "d"         => DoomKey.D,
                "e"         => DoomKey.E,
                "f"         => DoomKey.F,
                "g"         => DoomKey.G,
                "h"         => DoomKey.H,
                "i"         => DoomKey.I,
                "j"         => DoomKey.J,
                "k"         => DoomKey.K,
                "l"         => DoomKey.L,
                "m"         => DoomKey.M,
                "n"         => DoomKey.N,
                "o"         => DoomKey.O,
                "p"         => DoomKey.P,
                "q"         => DoomKey.Q,
                "r"         => DoomKey.R,
                "s"         => DoomKey.S,
                "t"         => DoomKey.T,
                "u"         => DoomKey.U,
                "v"         => DoomKey.V,
                "w"         => DoomKey.W,
                "x"         => DoomKey.X,
                "y"         => DoomKey.Y,
                "z"         => DoomKey.Z,
                "num0"      => DoomKey.Num0,
                "num1"      => DoomKey.Num1,
                "num2"      => DoomKey.Num2,
                "num3"      => DoomKey.Num3,
                "num4"      => DoomKey.Num4,
                "num5"      => DoomKey.Num5,
                "num6"      => DoomKey.Num6,
                "num7"      => DoomKey.Num7,
                "num8"      => DoomKey.Num8,
                "num9"      => DoomKey.Num9,
                "escape"    => DoomKey.Escape,
                "lcontrol"  => DoomKey.LControl,
                "lshift"    => DoomKey.LShift,
                "lalt"      => DoomKey.LAlt,
                "lsystem"   => DoomKey.LSystem,
                "rcontrol"  => DoomKey.RControl,
                "rshift"    => DoomKey.RShift,
                "ralt"      => DoomKey.RAlt,
                "rsystem"   => DoomKey.RSystem,
                "menu"      => DoomKey.Menu,
                "lbracket"  => DoomKey.LBracket,
                "rbracket"  => DoomKey.RBracket,
                "semicolon" => DoomKey.Semicolon,
                "comma"     => DoomKey.Comma,
                "period"    => DoomKey.Period,
                "quote"     => DoomKey.Quote,
                "slash"     => DoomKey.Slash,
                "backslash" => DoomKey.Backslash,
                "tilde"     => DoomKey.Tilde,
                "equal"     => DoomKey.Equal,
                "hyphen"    => DoomKey.Hyphen,
                "space"     => DoomKey.Space,
                "enter"     => DoomKey.Enter,
                "backspace" => DoomKey.Backspace,
                "tab"       => DoomKey.Tab,
                "pageup"    => DoomKey.PageUp,
                "pagedown"  => DoomKey.PageDown,
                "end"       => DoomKey.End,
                "home"      => DoomKey.Home,
                "insert"    => DoomKey.Insert,
                "delete"    => DoomKey.Delete,
                "add"       => DoomKey.Add,
                "subtract"  => DoomKey.Subtract,
                "multiply"  => DoomKey.Multiply,
                "divide"    => DoomKey.Divide,
                "left"      => DoomKey.Left,
                "right"     => DoomKey.Right,
                "up"        => DoomKey.Up,
                "down"      => DoomKey.Down,
                "numpad0"   => DoomKey.Numpad0,
                "numpad1"   => DoomKey.Numpad1,
                "numpad2"   => DoomKey.Numpad2,
                "numpad3"   => DoomKey.Numpad3,
                "numpad4"   => DoomKey.Numpad4,
                "numpad5"   => DoomKey.Numpad5,
                "numpad6"   => DoomKey.Numpad6,
                "numpad7"   => DoomKey.Numpad7,
                "numpad8"   => DoomKey.Numpad8,
                "numpad9"   => DoomKey.Numpad9,
                "f1"        => DoomKey.F1,
                "f2"        => DoomKey.F2,
                "f3"        => DoomKey.F3,
                "f4"        => DoomKey.F4,
                "f5"        => DoomKey.F5,
                "f6"        => DoomKey.F6,
                "f7"        => DoomKey.F7,
                "f8"        => DoomKey.F8,
                "f9"        => DoomKey.F9,
                "f10"       => DoomKey.F10,
                "f11"       => DoomKey.F11,
                "f12"       => DoomKey.F12,
                "f13"       => DoomKey.F13,
                "f14"       => DoomKey.F14,
                "f15"       => DoomKey.F15,
                "pause"     => DoomKey.Pause,
                _           => DoomKey.Unknown
            };
        }
    }
}