//
// Copyright (C) 1993-1996 Id Software, Inc.
// Copyright (C) 2019-2020 Nobuaki Tanaka
// Copyright (C)      2024 Rudy Alex Kohn
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//

using ManagedDoom.Doom.Common;

namespace ManagedDoom.Doom.Info;

public static partial class DoomInfo
{
    public static DoomString[] SpriteNames =>
    [
        new("TROO"),
        new("SHTG"),
        new("PUNG"),
        new("PISG"),
        new("PISF"),
        new("SHTF"),
        new("SHT2"),
        new("CHGG"),
        new("CHGF"),
        new("MISG"),
        new("MISF"),
        new("SAWG"),
        new("PLSG"),
        new("PLSF"),
        new("BFGG"),
        new("BFGF"),
        new("BLUD"),
        new("PUFF"),
        new("BAL1"),
        new("BAL2"),
        new("PLSS"),
        new("PLSE"),
        new("MISL"),
        new("BFS1"),
        new("BFE1"),
        new("BFE2"),
        new("TFOG"),
        new("IFOG"),
        new("PLAY"),
        new("POSS"),
        new("SPOS"),
        new("VILE"),
        new("FIRE"),
        new("FATB"),
        new("FBXP"),
        new("SKEL"),
        new("MANF"),
        new("FATT"),
        new("CPOS"),
        new("SARG"),
        new("HEAD"),
        new("BAL7"),
        new("BOSS"),
        new("BOS2"),
        new("SKUL"),
        new("SPID"),
        new("BSPI"),
        new("APLS"),
        new("APBX"),
        new("CYBR"),
        new("PAIN"),
        new("SSWV"),
        new("KEEN"),
        new("BBRN"),
        new("BOSF"),
        new("ARM1"),
        new("ARM2"),
        new("BAR1"),
        new("BEXP"),
        new("FCAN"),
        new("BON1"),
        new("BON2"),
        new("BKEY"),
        new("RKEY"),
        new("YKEY"),
        new("BSKU"),
        new("RSKU"),
        new("YSKU"),
        new("STIM"),
        new("MEDI"),
        new("SOUL"),
        new("PINV"),
        new("PSTR"),
        new("PINS"),
        new("MEGA"),
        new("SUIT"),
        new("PMAP"),
        new("PVIS"),
        new("CLIP"),
        new("AMMO"),
        new("ROCK"),
        new("BROK"),
        new("CELL"),
        new("CELP"),
        new("SHEL"),
        new("SBOX"),
        new("BPAK"),
        new("BFUG"),
        new("MGUN"),
        new("CSAW"),
        new("LAUN"),
        new("PLAS"),
        new("SHOT"),
        new("SGN2"),
        new("COLU"),
        new("SMT2"),
        new("GOR1"),
        new("POL2"),
        new("POL5"),
        new("POL4"),
        new("POL3"),
        new("POL1"),
        new("POL6"),
        new("GOR2"),
        new("GOR3"),
        new("GOR4"),
        new("GOR5"),
        new("SMIT"),
        new("COL1"),
        new("COL2"),
        new("COL3"),
        new("COL4"),
        new("CAND"),
        new("CBRA"),
        new("COL6"),
        new("TRE1"),
        new("TRE2"),
        new("ELEC"),
        new("CEYE"),
        new("FSKU"),
        new("COL5"),
        new("TBLU"),
        new("TGRN"),
        new("TRED"),
        new("SMBT"),
        new("SMGT"),
        new("SMRT"),
        new("HDB1"),
        new("HDB2"),
        new("HDB3"),
        new("HDB4"),
        new("HDB5"),
        new("HDB6"),
        new("POB1"),
        new("POB2"),
        new("BRS1"),
        new("TLMP"),
        new("TLP2")
    ];
}